%{
% @file PacejkaMagicFormula.m
% @brief Implements the Pacejka Magic Formula for lateral tire forces.
% @author Miguel Marina
%}
%/**
% * @class PacejkaMagicFormula
% * @brief Implements the Pacejka Magic Formula for tire lateral force calculation.
% *
% * The PacejkaMagicFormula class provides methods to calculate the lateral force generated by a tire
% * based on slip angle and normal load using the Pacejka '96 Magic Formula. It encapsulates the
% * tire model parameters (B, C, D, E) and ensures that calculations remain within realistic bounds.
% *
% * @author Miguel
% * @version 1.0
% * @date 2024-10-04
% */
classdef PacejkaMagicFormula
    properties
        %/**
        % * @property B
        % * @brief Stiffness factor.
        % *
        % * Determines the slope of the lateral force curve at zero slip angle.
        % */
        B % Stiffness factor
        
        %/**
        % * @property C
        % * @brief Shape factor.
        % *
        % * Adjusts the curvature of the lateral force curve.
        % */
        C % Shape factor
        
        %/**
        % * @property D
        % * @brief Peak factor.
        % *
        % * Represents the peak lateral force achievable by the tire.
        % */
        D % Peak factor
        
        %/**
        % * @property E
        % * @brief Curvature factor.
        % *
        % * Influences the shape of the force-slip angle curve beyond the peak.
        % */
        E % Curvature factor
    end
    
    methods
        %/**
        % * @brief Constructor to initialize Pacejka parameters.
        % *
        % * Initializes a new instance of the PacejkaMagicFormula class with specified parameters.
        % *
        % * @param B Stiffness factor.
        % * @param C Shape factor.
        % * @param D Peak factor.
        % * @param E Curvature factor.
        % *
        % * @throws Error if the number of input arguments is not equal to four.
        % */
        function obj = PacejkaMagicFormula(B, C, D, E)
            % Constructor implementation...
            if nargin ~= 4
                error('PacejkaMagicFormula requires four parameters: B, C, D, E.');
            end
            obj.B = B;
            obj.C = C;
            obj.D = D;
            obj.E = E;
        end
        
        %/**
        % * @brief Calculates the lateral force using the Pacejka Magic Formula.
        % *
        % * This method computes the lateral force based on the slip angle and normal force
        % * using the Pacejka '96 Magic Formula. It ensures that the slip angle remains within
        % * reasonable physical bounds to maintain realistic force calculations.
        % *
        % * @param alpha Slip angle (radians).
        % * @param F_z Normal force on the tire (N).
        % *
        % * @return F_y The calculated lateral force (N).
        % *
        % * @warning If the slip angle exceeds ±90 degrees, it is capped to prevent unrealistic force values.
        % */
        function F_y = calculateLateralForce(obj, alpha, F_z)
            % Calculates the lateral force using the Pacejka Magic Formula
            % alpha: Slip angle (radians)
            % F_z: Normal force on the tire (N)
    
            % Ensure alpha is within reasonable bounds
            if abs(alpha) > pi/2
                alpha = sign(alpha) * pi/2;
                %warning('Slip angle exceeded ±90 degrees and was capped to ±90 degrees.');
            end
    
            % Pacejka Magic Formula
            F_y = obj.D * sin(obj.C * atan(obj.B * alpha - obj.E * (obj.B * alpha - atan(obj.B * alpha))));
        end
    end
end
